114 impl prisma signal middleware
sparcs-kaist/otlplus-server pull request #115
Opened 2024-05-12 06:14 UTC by Jiuuung

- 몇가지 질문사항과 확인하고 싶은 사항이 있어서 회의때 리뷰를 받는것도 좋을 것 같습니다.
- 아직 테스트는 못해봤습니다.
- 이전 middleware구현한 브랜치에 이어서 구현했습니다.

2024-05-15 14:00 UTC, inhibitor1217 reviewed
note (첨언)

- A와 B가 1:N일 때 B의 개수를 A의 필드에 저장해두기 위해서: B가 create/delete될 때마다 A.count에 +1, -1하는 패턴은 잘 사용하지 않습니다
  - 이유: 한번이라도 업데이트를 놓치거나 retry하면 그때부터 숫자가 잘 안맞게됨.
  - 한두 번 놓치거나 여러 번 retry하더라도 정합성이 맞도록 구현하는 좋은 방법은 그냥 count(B) 쿼리를 매번 하고 그 결과를 A.count에 저장해두는 것입니다.
  - 물론 A를 읽는 일이 B가 생성/삭제 되는 경우보다 훨씬 자주 일어나야 A.count를 기록해두는 의미가 있습니다. 그렇지 않다면 그냥 매번 count(B) 때리는게 나음

2024-05-15 14:03 UTC, inhibitor1217 commented on src/prisma/middleware/prisma.lecture.ts
여기서 하는 일이 lecture의 update 이후, 다시 lecture의 필드를 보고 이것저것 수정할 것들을 챙겨서 한번 더 lecture를 업데이트 하는것 같아요.
그러면 업데이트 이후 시점이 아니라 이전 시점에 필드를 교정해주는 것이 더 좋을 것 같습니다.

2024-05-23 14:42 UTC, LarryKwon commented on src/prisma/middleware/prisma.lecture.ts
> +
이거 이렇게 한 이유가 PrismaService에 constructor에 뭔가를 inject 받고 싶지 않게끔 하고 싶어서 그랬습니다.
나중에 Mock으로 테스트 같은 걸 할 때 PrismaService에 뭔가를 Inject 해야하는 상황이 생기면 복잡해질 거 같아서요.

2024-05-23 14:43 UTC, LarryKwon commented on src/prisma/middleware/prisma.timetablelecture.ts
> +        }
가능하면 map으로 돌리고 Promise.all로 해주면 좋을 거 같은데 어떻게 보세요

2024-05-26 03:02 UTC, Jiuuung commented on src/prisma/middleware/prisma.reviews.ts
> +  private async reviewDeletedMiddleware(result: any) {
삭제하는 과정에서 레포지토리에서 리턴 받을 값을 별도로 설정하지 않는다면 기본적으로른 삭제한 객체 그 자체를 리턴해준다고 합니다.

2024-05-27 08:18 UTC, Jiuuung commented on src/prisma/middleware/prisma.lecture.ts
여기서 하는 작업이 lecture의 제목과 관련이 없는 필드들이 업데이트 되었을 때 제목과 관련된 부분들이 불일치하는 경우 맞춰주는 과정인것 같습니다. 그래서 업데이트 이후 시점으로 두어도 괜찮을 것 같습니다.

2024-07-19 05:26 UTC, LarryKwon requested changes
전체적으로 다 괜찮고, 자잘하게 고칠 것들인데, 몇 가지 추가 or 크게 변경되어야할 부분
- 내 기억에 저번에 increase, decease 하지 말고 그냥 그 때 그 때 다 세기로 했지 않나? 그게 오히려 정합이 잘 맞을 거 같은데
- increase,decrease 할 거면 pessimistic lock을 걸고 select 한 후에 update 쳐줘야함. 안 그러면 동시성 제어가 안 됨

2024-07-19 05:26 UTC, LarryKwon commented on src/prisma/middleware/prisma.reviews.ts
> +      })
여기서 findUniqueorThrow하는데 throw에 대한 처리가 없어

2024-07-19 05:26 UTC, LarryKwon commented on src/prisma/middleware/prisma.lectureprofessors.ts
> +    );
이런 곳에서 throw해주는거 잡아주던가, 아니면 lectureGetWeight 쪽에서 뭔가를 해줘야할듯?

2024-07-19 05:26 UTC, LarryKwon commented on src/prisma/middleware/prisma.lectureprofessors.ts
> +    ).year;
여기도 throw 코드 방어 없음

2024-07-19 05:26 UTC, LarryKwon commented on src/prisma/middleware/prisma.reviews.ts
> +  private async reviewDeletedMiddleware(result: any) {
그럼 문제가 없는거겠군여

2024-07-23 04:57 UTC, Jiuuung commented on src/prisma/middleware/prisma.lectureprofessors.ts
> +    return true;
합쳤어용

2024-07-30 08:25 UTC, LarryKwon approved these changes

2024-07-30 08:25 UTC, LarryKwon commented on src/prisma/middleware/prisma.reviewvote.ts
> +  }
이 친구는 트랜잭션 걸고 안 해줘도 되나?

2024-07-31 15:20 UTC, merged