Refactor/interface convention
sparcs-kaist/otlplus-server pull request #120
Opened 2024-07-24 22:22 UTC by doxylee

2024-07-24 22:26 UTC, doxylee commented
@pbc1017 여기 제가 주석 달아둔 내용 혹시 확인 가능하신가요?
https://github.com/sparcs-kaist/otlplus-server/pull/120/commits/4e2d53f5465f1b7a6795a109156a1d6e9a7cf972

전에 작성해주셨던 부분이 컨벤션에 맞지 않는 부분이 있어 고쳐보았는데, getUserLecturesByYearSemester에서 department까지 include 필요한건지 궁금합니다

2024-07-31 13:43 UTC, LarryKwon commented on src/common/interfaces/IPlanner.ts
> +    @IsArray()
다른 부분에는 무슨무슨 QueryDto라고 되어있던데 여기는 그냥 Query라서.. 혹시 어떤게 더 나을까요?

2024-07-31 13:44 UTC, LarryKwon commented on src/common/interfaces/ITimetable.ts
> +  }
여기도 앞에서는 Body라고 하신 부분이 있어서 어떤게 더 나을까 싶어서 여쭤봅니다.

2024-07-31 13:59 UTC, LarryKwon requested changes
serializer 쪽에 실행 변경된거 있다고 하셨는데, 제가 보기에는
1. return type, 파라미터 타입 바뀐거
2. Basic, Detail이 구분되면서 함수를 자르는 것들
말고는 없어보이는데 혹시 더 있으신가요?

2024-07-31 13:59 UTC, LarryKwon commented on src/common/interfaces/serializer/feeds.serializer.ts
> +    } as IFeed.ReviewWrite;
이거는 혹시 왜 as 붙어있나요 타입이 안 맞으신건지...

2024-08-01 08:57 UTC, doxylee commented on src/common/interfaces/serializer/feeds.serializer.ts
> +    } as IFeed.ReviewWrite;
확인해보니 없어도 문제 없네요. 지우겠습니다.

2024-08-01 09:01 UTC, doxylee commented
> serializer 쪽에 실행 변경된거 있다고 하셨는데, 제가 보기에는
> 
> 1. return type, 파라미터 타입 바뀐거
> 2. Basic, Detail이 구분되면서 함수를 자르는 것들
>    말고는 없어보이는데 혹시 더 있으신가요?

네 말씀하신게 전부입니다.

2024-08-01 09:18 UTC, doxylee commented
> 그 전반적으로 궁금한게 두 개 정도 있는데,
> 
> 1. QueryDto vs Query / Body 이렇게 나뉘어져 있는데 1) 이걸 한 가지로 통일할 필요가 있을지 2) 한다면 어느게 더 나을지 궁금하고
> 2. Response 하는데 있어서, Response라는 걸로 묶여있는 친구들이 있고 아닌 친구들이 있던데, 이것도 마찬가지로 1) 통일을 할 필요가 있을지 2) 한다면 어떤게 나을지 의견 여쭤봅니다.
> 
> 통일은 함수 단위에서도 있지만, 그에 맞춰서 패키지도 정리해야할 수도 있으니까, 패키지까지 고려해서 의견 부탁드려요!

저도 리팩토링 진행하면서 기준이 흔들리던 부분입니다. I로 시작하는 네임스페이스에 있는 것들은 사실상 전부 DTO라고 보면 되는데, 그렇다면 길이를 줄이기 위해 DTO를 뗄 수도 있고, 그럼에도 DTO라고 명시하는 게 낫다고 보면 DTO를 붙이는 것이 낫습니다.

Response라고 되어있는 경우는 Basic, Detail 등 어떤 이름을 붙이는 것이 좋을지 난감해 원래 있던 이름대로 놔두어 생기게 되었습니다.

2024-08-01 09:43 UTC, doxylee commented on src/common/interfaces/IPlanner.ts
> +    @IsArray()
Dto 붙이는 방식으로 모두 고쳤습니다

2024-08-01 09:44 UTC, doxylee commented on src/common/interfaces/ITimetable.ts
> +  }
Dto 붙이는 방식으로 모두 고쳤습니다.

2024-08-01 09:44 UTC, doxylee commented
request로 사용되는 경우 전부 Dto를 붙이도록 변경했습니다. Response라고 되어있던 부분도 알맞게 변경했습니다.

2024-08-03 11:37 UTC, LarryKwon approved these changes

2024-08-03 11:42 UTC, merged