Feat: add get lecture review api
sparcs-kaist/otlplus-server pull request #39
Opened 2023-08-24 16:27 UTC by Jiuuung

lecture review 구현 끝
현재 lecture 찾고 review include해서 가져오는 방식인데 그냥 바로 review_review에서  lecture id로 review찾는 거랑 둘중에 어떤게 더 빠를지는 모르겠네요. + 로그인이 필요 없는 api인데 auth-cookie가 없으면 Unauthorized error가 뜹니다...

2023-08-27 16:09 UTC, LarryKwon requested changes

2023-08-27 16:09 UTC, LarryKwon commented on src/common/schemaTypes/types.ts
> +const lectureReviews = Prisma.validator<Prisma.subject_lectureArgs>()({
LectureReviewDetails로 바꾸는건 어때?

2023-08-27 16:09 UTC, LarryKwon commented on src/modules/lectures/lectures.service.ts
> +          const isLiked: boolean = await this.reviewsRepository.isLiked(
여기에 await 걸어거리면 아마 비동기가 아니라 동기로 진행될 걸?
할거면 await를 떼고 .then으로 해서 받아내야할거야

2023-08-27 16:11 UTC, LarryKwon commented
@Public이라는 데코레이터가 있어! 그거 사용하면 인증 필터를 안 거칩니다.

2023-08-27 23:57 UTC, Jiuuung commented on src/modules/lectures/lectures.service.ts
> +          const isLiked: boolean = await this.reviewsRepository.isLiked(
동기식으로 진행하려고 하는게 맞긴 한데 혹시 문제가 될까??

2023-09-26 10:41 UTC, ddungiii commented
@Jiuuung 구두로 소통한대로 변경사항 따로 반영해주세요~!

2023-09-26 10:41 UTC, merged