feat: read course
sparcs-kaist/otlplus-server pull request #77
Opened 2024-02-21 13:19 UTC by ddungiii

`POST api/courses/:id/read`

2024-02-21 21:26 UTC, doxylee requested changes

2024-02-21 21:26 UTC, doxylee commented on src/modules/courses/courses.service.ts
> +        })?.latest_read_datetime;
이거.. 위쪽에 filterByRequest에서 include: {subject_courseuser: true} 하면서 해당 course에 연결된 모든 subject_courseuser 가져오는 것 같은데, 성능에 문제 생기지 않을까요?
django에서는 전부 가져오는 게 아니라 나중에 find 메서드 비슷하게 호출하면 그때 해당 유저에 대해서만 query가 날아갔을지도 모르겠는데, prisma는 처음부터 전부 들고오게 되어있어서 문제될 것 같은데..

2024-02-21 21:26 UTC, doxylee commented on src/modules/courses/courses.service.ts
> +        })?.latest_read_datetime;
저라면 filterByRequest에 reqUserId 파라미터 추가하고
subject_courseuser: {where: {user_profile_id: reqUserId }} 이런 식으로 요청한 유저에 대한 정보만 포함하도록 만들 것 같네요.

2024-02-28 11:19 UTC, ddungiii commented on src/modules/courses/courses.service.ts
> +        })?.latest_read_datetime;
네네 요거 따로 PR로 뺄게요! #78

2024-02-28 13:25 UTC, doxylee approved these changes

2024-02-28 13:25 UTC, merged