Implement fetching related reviews of a lecture
sparcs-kaist/otlplus-server pull request #82
Opened 2024-03-03 13:33 UTC by inhibitor1217

## Summary

- Implement `GET /api/lectures/:lectureId/related-reviews` ([Link](https://www.notion.so/sparcs/api-lectures-lectureId-related-reviews-7123896458c24573b45be2e665cfd8af?pvs=4))
  - [기존 구현](https://github.com/sparcs-kaist/otlplus/blob/8086f13604f0832fbfc3fd5fa977d61a60c311d5/apps/subject/views.py#L246-L267) 을 참고하면, "related review" 란 대상 lecture와 비교했을 때 course와 professor가 동일한 review를 말합니다.

2024-03-07 14:00 UTC, LarryKwon submitted a review, later dismissed

2024-03-07 14:00 UTC, LarryKwon commented on src/common/interfaces/dto/lecture/lecture.request.dto.ts
> +}
바로 위에도 같은게 있어서... 혹시 해당 부분 PaginationDto로 분리하는건 어떻게 생각하세요?

2024-03-07 14:00 UTC, LarryKwon commented on src/prisma/repositories/review.repository.ts
> +      },
혹시 이 부분 ECourse나 ELecture로 바꿔주실 수 있으실까요?

2024-03-13 10:19 UTC, inhibitor1217 commented on src/common/interfaces/dto/lecture/lecture.request.dto.ts
> +}
- 다른 부분도 중복으로 적혀있어서 함께 분리해도 좋을 것 같아요
- 이슈로 만들어두면 될까요?

2024-03-20 10:56 UTC, inhibitor1217 commented on src/common/interfaces/dto/lecture/lecture.request.dto.ts
> +}
#84 참고하여 `IReview.LectureReviewsQueryDto` 사용하도록 할게요

2024-03-20 12:34 UTC, doxylee requested changes

2024-03-20 12:34 UTC, doxylee commented on src/prisma/repositories/review.repository.ts
> +      },
include: EReview.Details.include로 더 줄이는 것도 가능합니다!

2024-03-20 12:34 UTC, doxylee commented on src/prisma/repositories/review.repository.ts
> +    });
src/common/utils/search.utils.ts에 있는 orderFilter 사용하시면 좋을 것 같습니다!

2024-03-20 12:34 UTC, doxylee commented on src/modules/lectures/lectures.service.ts
> +    const MAX_LIMIT = 100;
DEFAULT_LIMIT 으로 이름을 변경하면 더 어울릴 것 같습니다!

2024-03-20 12:34 UTC, doxylee commented on src/modules/lectures/lectures.controller.ts
> +  ): Promise<(ReviewResponseDto & { userspecific_is_liked: boolean })[]> {
IReview.Basic (??) 으로 바꿔줘도 될 것 같은데 IReview.Basic이 이름이나 내부 정의가 조금 문제가 있는 것 같아요. 가능하시면 고쳐주시면 정말 감사할 것 같고, 아니면 TODO 주석만 달아주시거나 나중에 리팩토링하면서 고쳐지도록 그냥 현 상태로 놔두셔도 될 것 같아요.

2024-03-20 12:53 UTC, inhibitor1217 commented on src/prisma/repositories/review.repository.ts
> +    });
없던게 많이 생겼네용 👍

2024-03-27 12:08 UTC, doxylee approved these changes

2024-03-27 12:13 UTC, merged