add: share controller & service
sparcs-kaist/otlplus-server pull request #92
Opened 2024-03-13 03:53 UTC by pbc1017

2024-03-20 13:15 UTC, doxylee requested changes

2024-03-20 13:15 UTC, doxylee commented on src/prisma/repositories/timetable.repository.ts
> +        },
ETimetable.WithLectureClasstimes 로 정의해주어 사용하면 좋을 것 같아요. 다른 E로 시작하는 엔티티 파일들 참고하시면 됩니다.

2024-03-20 13:18 UTC, inhibitor1217 commented on src/modules/share/share.service.ts
> +    return canvas.toBuffer();
https://github.com/Automattic/node-canvas?tab=readme-ov-file#canvastobuffer

mimeType 옵션 주기

2024-03-20 13:23 UTC, inhibitor1217 commented on src/modules/share/share.controller.ts
> +    }
`createTimetableImage` 안에서 적절한 exception도 날리는 경우가 있는데 (not found 같은것)
여기에서 잡아서 다시 500 에러로 만들고 있어서 고쳐져야 할 것 같아요~

2024-03-20 13:28 UTC, inhibitor1217 commented on src/modules/lectures/lectures.service.ts
> +    return `${profNameList[0]} 외 ${profNameList.length - 1} 명`;
여기서도 언어 고려되었어야 할 것 같아요

2024-03-20 13:29 UTC, inhibitor1217 commented
svc / repo 쪽 패턴은 @doxylee 님 믿고있었다구 로 가보겠습니다 🙇

2024-03-20 13:34 UTC, doxylee commented
헉;;

2024-03-27 13:31 UTC, doxylee approved these changes

2024-03-27 13:36 UTC, merged