Implement reorder planner orderings
sparcs-kaist/otlplus-server pull request #95
Opened 2024-03-20 11:38 UTC by inhibitor1217

## Summary

- [졸업플래너 - planner reorder 기능](https://www.notion.so/sparcs/api-users-userId-planners-plannerId-reorder-a8e89a86133743a996f56a6756f68efe?pvs=4)
- [기존 구현](https://github.com/sparcs-kaist/otlplus/blob/8086f13604f0832fbfc3fd5fa977d61a60c311d5/otlplus/urls.py#L86-L87)

2024-03-20 12:54 UTC, doxylee requested changes

2024-03-20 12:54 UTC, doxylee commented on src/prisma/repositories/planner.repository.ts
> +    }
repository쪽에서는 http exception보다는 null로 돌려주는 편이 낫지 않을까요?

2024-03-20 12:54 UTC, doxylee commented on src/prisma/repositories/planner.repository.ts
> +  }
원래 코드 보면 하나씩 shift하는 로직이 들어가야 하는 것 같습니다. 확인 부탁드려요!
https://github.com/sparcs-kaist/otlplus/blob/8086f13604f0832fbfc3fd5fa977d61a60c311d5/apps/planner/services.py#L6

2024-03-20 13:39 UTC, inhibitor1217 commented on src/prisma/repositories/planner.repository.ts
> +    }
Planner repository에서만 throw 하고 있어서,
이 부분을 null return으로 조정하고 planner 복제 도중에는 graceful 하게 처리하도록 (없는 item은 무시) 했습니다.

2024-03-27 13:46 UTC, inhibitor1217 commented on src/prisma/repositories/planner.repository.ts
> +  }
https://github.com/sparcs-kaist/otlplus/blob/8086f13604f0832fbfc3fd5fa977d61a60c311d5/apps/planner/services.py#L10-L21

원래 코드에서는 한 쿼리에 해결하던 부분인데 prisma에서는 한 쿼리로 해결하려면 raw query를 쓸 수밖에 없을 것 같아 두 개로 나누어 처리했습니다. (reorder하는 item의 order 변경, shift되는 주변 item들 한번에 업데이트)

2024-03-31 11:04 UTC, LarryKwon approved these changes

2024-03-31 11:04 UTC, merged